# Generated by Django 5.0.6 on 2024-07-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, verbose_name="To'liq ism")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('message', models.TextField(verbose_name='Maqsad')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Yozilgan vaqt')),
                ('status', models.CharField(choices=[('Kontakt yuborilgan', 'Kontakt yuborilgan'), ('Rad etish', 'Rad etish'), ("Xabar o'qildi", "Xabar o'qildi"), ('Kelishilgan', 'Kelishilgan'), ('Zakaz olingan', 'Zakaz olingan'), ('Javob berilgan', 'Javob berilgan')], default='Kontakt yuborilgan', max_length=30, verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'Kontakt ',
                'verbose_name_plural': 'Kontaktlar',
                'db_table': 'contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
